### ISSUE TITLE
not working on pi 3

### ISSUE THREAD

**Issue by udaykumar78** [Surf-N-Code/noia-node-terminal#1]
problem in starting npm
npm installation is not done in home folder,bcoz of some issues.

**Comment by iBandCrypto** [comment]
Not working in Raspberry 3 B+ 
I am not technical but followed the instructions. I got stuck running npm

pi@raspberrypi:~/noia-node-terminal $ npm start

> @noia-network/node-cli@0.2.1 start /home/pi/noia-node-terminal
> node ./dist/index.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/pi/noia-node-terminal/dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @noia-network/node-cli@0.2.1 start: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @noia-network/node-cli@0.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-08-22T18_51_17_461Z-debug.log
